### ISSUE TITLE
Where to place migration?

### ISSUE THREAD

**Issue by sasweb** [Thibaud05/adonisjs-docker-compose#1]
Hi,
I'm just wondering where to place the migration `adonis migration:run --force`.

**Comment by Thibaud05** [comment]
Hi,
I just run the migration into node container :

Start a new cmd line
```
docker exec -it appname-nodejs /bin/bash
```

Run the migration
```
adonis migration:run
```

Run the seeder
```
adonis seed
```

**Comment by pawelsas** [comment]
Sorry for asking again but I tried to use your boilerplate for my next.js integration.
So after running `npm install` I need to execute `npm run builld` for the next.js build and `npm start` which actually runs `node server.js`.

I have replaced your `command: adonis serve --dev --polling` by `command: node server.js` and added `RUN npm run build` to my Dockerfile. 

Unfortunately Docker tells me after running this on `docker-compose ps` that my migration and api services are down (Exit status 1).
